livekit/audio_source.py
livekit/audio_stream.py
livekit/participant.py
livekit/room.py
livekit/track.py
livekit/track_publication.py
livekit/video_frame.py
livekit/video_source.py
livekit/video_stream.py

Doing absolute imports from livekit module can trigger circular import exceptions.
This PR replace all absolute imports from livekit by relative imports.

Avoid circular imports

---

README.md
examples/basic_room.py
examples/e2ee.py
examples/face_landmark/face_landmark.py
examples/publish_hue.py
examples/publish_wave.py
examples/whisper/whisper.py
livekit/_ffi_client.py
livekit/_utils.py
livekit/audio_source.py
livekit/audio_stream.py
livekit/participant.py
livekit/room.py
livekit/video_stream.py

- Always ensure we keep the order from the FfiServer
- So the complex logic can be handled from Rust (for synchronisation)
- E.g: the ffi server ensure that the `LocalTrackPublished` callback is sent before the `LocalTrackPublished` event
- We know use only one FfiQueue per room (So it is possible for us to keep things synchronised)
The room musts be used inside one event_loop (specified inside the ctor)
AudioStream & VideoStream can be used on other event_loops (making it easy to have another IO thread for e.g)

fix: keep events order

---

examples/publish_wave.py
livekit/audio_stream.py
livekit/room.py
livekit/video_stream.py

also disable e2ee on publish_wave example

fix: correctly unsubscribe to the ffi queue

---

livekit/room.py

This PR sets the rparticipant variable to None in the `data_received` event. This addresses the error `Local variable referenced before assignment`. This may have negative effects in users callback functions if there isn't a None type check before referencing participant.

Set rparticipant variable before emit event

---

examples/e2ee.py
examples/publish_hue.py
livekit-rtc/livekit/rtc/video_source.py

Fix #85 
The VideoSource resolution is used on the Rust side to define the needed simulcast layers

fix: add resolution arguments to VideoSource

---

livekit-api/livekit/api/access_token.py

fix: access token VideoGrants types

---

livekit-protocol/generate_proto.sh

also replace `/bin/bash` with `/usr/bin/env bash` for portability

fix#livekit-protocol: generate_proto.sh

---

livekit-rtc/livekit/rtc/_ffi_client.py

LIVEKIT_RTC_DEBUG will enable libwebrtc & livekit debug logs.
Otherwise it is too noisy even in debug logs. The main motivation for this PR is for the devex of agents

debug logs must be explicitly enabled

---

livekit-rtc/livekit/rtc/room.py

should fix the bug when receiving messages from the server: this allows Python to fail gracefully to retrieve the remote participant.

room: allow RemoteParticipant to be None

---

README.md

The link to the wave example was opening the hue example. This fixes the link! 
<sub>(also some other line-ending changes added automatically by Github)</sub>

Fix wave example link in README

---

README.md
livekit-rtc/livekit/rtc/chat.py

Also updated README with chat usage
(most of the diff is CRLF -> LF)

Remove unused method in ChatManager to reduce confusion

---

examples/multiple_connections.py
livekit-rtc/livekit/rtc/_ffi_client.py

When a client closes the runloop (i.e. with asyncio.run) before cleanly tearing down resources, the FfiQueue would crash when any event is dispatched.
Fixes #218

Avoid crashing the FfiQueue when subscriber is not cleaned up

---

livekit-rtc/livekit/rtc/audio_source.py

resetting to -0.05 on release also breaks things, so it was left at 0.0.

only subtract 50ms from stream queue once

---

livekit-rtc/livekit/rtc/audio_frame.py
livekit-rtc/livekit/rtc/participant.py
livekit-rtc/livekit/rtc/room.py
livekit-rtc/livekit/rtc/track.py
livekit-rtc/livekit/rtc/track_publication.py
livekit-rtc/livekit/rtc/video_frame.py

add __repr__
add AudioFrame.to_wav_bytes
added some docstrings (driveby)

quality of life improvements

---

livekit-api/livekit/api/access_token.py
livekit-rtc/livekit/rtc/_proto/ffi_pb2.pyi
livekit-rtc/livekit/rtc/_proto/handle_pb2.pyi
livekit-rtc/livekit/rtc/participant.py
livekit-rtc/livekit/rtc/video_frame.py

Following deprecation warning was raised:
```
/usr/local/lib/python3.12/site-packages/livekit/api/access_token.py:152: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
(datetime.datetime.utcnow() + self.ttl).utctimetuple()
```
datetime.utcnow() is being deprecated in Python 3.12 as it returns a naive datetime object without timezone information. Replace with datetime.now(UTC) to use an explicit timezone-aware object, preventing potential timezone ambiguity issues.
In access_token.py, updated the token expiration calculation to use the recommended timezone-aware approach.

update datetime.utcnow() to use UTC timezone-aware object

---

examples/participant_attributes.py
livekit-rtc/livekit/rtc/event_emitter.py
livekit-rtc/tests/test_emitter.py

Some reasonable feedback arrived in community that it's confusing that you can't use async handlers for events in this SDK.  
I looked at the complexity of supporting async handlers and it seems like the largest barrier would be how to await them?  Either the `.emit()` method would need to become async and await them directly, which sounds wrong as you wouldn't expect `.emit()` to block on long-running applications, or you'd need to create tasks to run them asynchronously but then you have the question of where to collect the tasks and how to cancel them or cleanup.
I think it's reasonable to pass this onto the end-developer to collect their own async tasks but we can make it easier to discover this and harder to write subtle bugs. Raising an error with an explanation and workaround …

Raise error if EventEmitter used with async callback

---

README.md
examples/room_example.py

See issue here #309
https://github.com/livekit/python-sdks/issues/309
This fixes the readme example and adds a more complete example so users don't waste time trying to use an invalid example.

fixes #309 example in readme and makes a more complete example

---

livekit-rtc/livekit/rtc/participant.py

fixes https://github.com/livekit/python-sdks/issues/317

fixed unpublish track error by adding stop_on_unpublish value

---

examples/video-stream/README.md
examples/video-stream/audio_wave.py
examples/video-stream/video_play.py

also passing room name/file from cli

updated AVSynchronizer readme

---

examples/video-stream/video_play.py
livekit-rtc/livekit/rtc/synchronizer.py

Improved the video play example:
1. log the timestamps of the video and audio frames
2. add reset for av sync after the video finished

fix av sync example

---

livekit-rtc/livekit/rtc/_ffi_client.py

I've done some profiling and found that `bytes(data_ptr[: int(data_len)])` is an expensive operation and can be done by `ctypes.string_at` instead.
The benchmark result:
```
Correctness: Pass
Method 1 (slicing) avg time: 0.016509 seconds
Method 2 (string_at) avg time: 0.000130 seconds
```
The benchmarking code:
```
import ctypes
import random
import time
def create_cdata():
test_data = bytes(
random.getrandbits(8) for _ in range(10**6)
)  # 1 MB of random data
data_len = len(test_data)
c_array = (ctypes.c_uint8 * data_len)(*test_data)
data_ptr = ctypes.cast(c_array, ctypes.POINTER(ctypes.c_uint8))
return data_ptr, data_len
def benchmark_and_validate(iterations=100):
total_time1 = 0.0
total_time2 = 0.0
is_correct = True
for _ in range(iterations):
data_ptr, data_len=create_cdata() …
```

use ctypes.string_at for faster copying bytes

---

.github/workflows/check-types.yml
.github/workflows/tests.yml
livekit-rtc/livekit/rtc/audio_frame.py
livekit-rtc/livekit/rtc/synchronizer.py
livekit-rtc/livekit/rtc/video_frame.py

- this package still doesn't depend on pydantic 
- data is serialized in b64

add pydantic support to rtc.VideoFrame & rtc.AudioFrame

---

examples/data-streams/data_streams.py
livekit-rtc/livekit/rtc/data_stream.py
livekit-rtc/livekit/rtc/participant.py
livekit-rtc/livekit/rtc/room.py

addresses feedback from @theomonnom on https://github.com/livekit/python-sdks/pull/347 after it got merged

Rework data stream API

---

livekit-rtc/livekit/rtc/__init__.py
livekit-rtc/livekit/rtc/data_stream.py
livekit-rtc/livekit/rtc/participant.py

- removes mid-stream chunk overrides
- this allows for `writer.write(text)` to perform auto chunking, mirroring the same behaviour as on byte streams
- also allows for send_text to be a thin auto-closing wrapper over stream_text
- allows for `text_reader` to be a simple async iterable of type `str` instead of the `TextStreamUpdate` data class (again improved consistency with how byte stream reader works)

Add auto chunking for text stream writer

---

livekit-rtc/livekit/rtc/_utils.py
livekit-rtc/livekit/rtc/data_stream.py
livekit-rtc/livekit/rtc/participant.py

`stream_id` is required for TTS to be able to override previously sent messages with the same stream_id
`sender_identity` allows an agent to override the sending participant. Main usecase is also transcriptions.

Add stream_id and sender_identity to stream_text params

---

livekit-api/livekit/api/livekit_api.py

this allows the Agent framework to manage the lifecycle of the session

Allow custom aiohttp session

---

livekit-rtc/livekit/rtc/participant.py

improve types & allow to return None

improve RPC types 

---

livekit-api/livekit/api/access_token.py
livekit-api/livekit/api/room_service.py

Grant required https://github.com/livekit/livekit/blob/master/pkg/service/auth.go#L228

add missing auth grant to forward participant

---

examples/data-streams/data_streams.py
livekit-api/README.md
livekit-api/livekit/api/room_service.py
livekit-rtc/README.md
livekit-rtc/livekit/rtc/__init__.py

updated the readmes and package descriptions for api and rtc packages, and fixed the data stream example

example and docs tweaks

---

livekit-rtc/livekit/rtc/data_stream.py

This PR fixes a bug in `ByteStreamWriter` where the first data chunk was incorrectly sent with **_chunk_index = 1_** instead of the expected 0.
**Problem:**
As described in Issue #430 , the `_next_chunk_index` was incremented before being used in the write method, causing incompatibility with clients (like the Unity SDK's ByteStreamReader) that expect stream chunk indices to start at 0. 
This differs from the behavior of `TextStreamWriter`, which correctly starts at index 0.
**Changes:**
The ByteStreamWriter.write method has been modified to:
Use the current value of `_next_chunk_index` (which starts at 0 in `BaseStreamWriter`) for the chunk_index.
Increment `_next_chunk_index` after the chunk message has been sent via `_send_chunk`.
This aligns the behavior with `TextStreamWriter` and …

Fix: Start ByteStreamWriter chunk index at 0 #430

---

README.md

I surprised `livekit` and `livekit-api` have different versioning. And I think it can be useful to see versions of both in Readme to avoid confusions for others.

Readme: added badge for livekit-api

---

livekit-api/livekit/api/sip_service.py

LiveKit's SIPDispatchRuleUpdate is a protobuf message where fields like `trunk_ids` must be set during initialization.
Attempting to assign `trunk_ids` after instantiation raised the following runtime error:
AttributeError: Assignment not allowed to message, map, or repeated field "trunk_ids" in protocol message object.
This is due to protobuf’s restriction against direct assignment to message or repeated fields after construction.
Set `trunk_ids` during SIPDispatchRuleUpdate construction using `ListUpdate(set=...)`, ensuring proper initialization and serialization by the protobuf engine.

[fix] trunk_ids Assignment Error in SIPDispatchRuleUpdate

---

livekit-api/livekit/api/access_token.py

The `InferenceGrant` is required to perform LLM inference in the backend. This will be used by the agents SDK.

Adding the inference grant

---

examples/data-streams/data_streams.py

Fix for error in data streams examples for byte & text stream handlers.

fixed calls from 'set' to 'register'
